### ISSUE TITLE
WORKSPACE RPM URL does not take into account repo metadata

### ISSUE THREAD

**Issue by stefanha** [rmohr/bazeldnf#71]
I have a repo where rpm files are kept at a separate location from the metadata:
```yaml
repositories:
- arch: x86_64
  baseurl: https://brew-task-repos.engineering.redhat.com/repos/official/qemu-kvm/8.2.0/5.el9/x86_64/
  name: qemu-kvm-x86_64
  gpgcheck: 0
  repo_gpgcheck: 0
```

The repo metadata is available at the baseurl, but the actual rpm files are located elsewhere and referenced in the primary.xml.gz file:
```xml
<package ...>...<location xml:base="https://download.eng.bos.redhat.com/brewroot/vol/rhel-9/packages/qemu-kvm/8.2.0/5.el9/x86_64" href="qemu-guest-agent-8.2.0-5.el9.x86_64.rpm"/>
```

Notice that the repo baseurl and the rpm file URLs are two different domain names.

bazeldnf currently generates the WORKSPACE rpm file URL by concatenating the baseurl with the rpm filename. This approach does not work since the rpm files are not alongside the repo metadata.

Is it possible to update bazeldnf to honor the `<location xml:base>` attribute when building URLs?

Shoutout to @andreabolognani who I discussed this issue with.
